-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v2.2.3'
    hooks:
    -   id: check-merge-conflict
    -   id: end-of-file-fixer  # ensure files only end in a newline

-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.5.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v2.3.1'
    hooks:
    -   id: pylint

-   repo: local
    hooks:
    -   id: tests
        name: Run Tests
        entry: pytest --verbose
        language: system
        types: [python]
        # stages: [push]
